#!/bin/bash
virtualenv venv
source venv/bin/activate
pip install django~=1.11
pip install -e ../

mkdir media static
python manage.py makemigrations
python manage.py makemigrations photos
python manage.py migrate
python manage.py collectstatic --noinput
echo "Setup Complete."
